apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: test-repo
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/nabuskey/example-kustomize-repo
  ref:
    branch: main
