apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: test
  namespace: flux-system
spec:
  kubeConfig:
    secretRef:
      name: xppocca1-ekscluster
  interval: 5m
  path: "./kustomize/dev"
  prune: true
  sourceRef:
    kind: GitRepository
    name: test-repo
  wait: true
  timeout: 2m

